name: Jason Wenk Blog
favicon: null
layout_spectrum: 0.444165542954579
typography_spectrum: 0.94724
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404041'
    - '#8dc63f'
    - '#000000'
    - '#00ff00'
    - '#808000'
  brandStrength: 0.6875
  lightness: 0.9793346298392862
  saturation: 0.5532385769765824
  rhythmicContrast: 0.32277651713229716
purpose: []
