name: Jason Wenk Blog
favicon: null
layout_spectrum: 0.444165542954579
typography_spectrum: 0.9245655017439276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8928771391510963
  lightness: 0.9793346298392862
  saturation: 0.5532385769765824
  rhythmicContrast: 0.32277651713229716
purpose: []
